# Generated by Django 5.1.6 on 2025-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('rating_sentiment', models.CharField(max_length=10)),
                ('review_sentiment', models.CharField(max_length=10)),
                ('overall_sentiment', models.CharField(max_length=10)),
            ],
        ),
    ]
