# Generated by Django 5.1.6 on 2025-08-12 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('rating_sentiment', models.CharField(max_length=10)),
                ('review_sentiment', models.CharField(max_length=10)),
                ('overall_sentiment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReviewText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.TextField()),
                ('review_rating', models.FloatField(blank=True, null=True)),
                ('review_text', models.TextField()),
                ('movie', models.ForeignKey(db_column='imdb_id', on_delete=django.db.models.deletion.CASCADE, to='movies.moviereview', to_field='imdb_id')),
            ],
        ),
    ]
